# docker-compose.yml example

#
## WARNING: There is no way to combine all GPU, this is to target
##          one specific GPU out of your multi-gpu setup so other
##          GPU's can work on other tasks (development?)
##
## WARNING: Currently only nvidia supported.
##
## WARNING: This is not tested. I have too many GPU's :D
#

services:
  sd-forge:
    extends:
      file: docker-compose.yaml
      service: sd-forge
    command:
      # do not touch, this starts the startup script inside container
      - /app/webui-docker.sh
      # leave below, we bind it to 127.0.0.1 below on the host
      # experimenting removal of this, to bind back to localhost inside container
      #- --server-name=0.0.0.0
      # REMOVE ABOVE BEFORE FINAL MERGE FOR v1.0.0
      ## ONLY UNCOMMENT if having issues generating images
      #- --always-low-vram
      # COMMENT BELOW if you uncomment above (???)
      - --vae-in-fp32
      # do not touch below 3 lines, they help :)
      - --cuda-malloc
      - --force-upcast-attention
      - --pin-shared-memory
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
    # CHANGE BELOW TO YOUR GPU VRAM (IF UNSURE COMMENT IT OUT!)
    shm_size: '8gb'
  # END OF FILE
