# docker-compose.yml example

#
## WARNING: There is no way to combine all GPU, this is to target
##          one specific GPU out of your multi-gpu setup so other
##          GPU's can work on other tasks (development?)
##
## WARNING: Currently only nvidia supported.
##
## WARNING: This is not tested. I have too many GPU's :D
#

services:
  sd-forge:
    extends:
      file: docker-compose.yaml
      service: sd-forge
    command:
      # do not touch, this starts the startup script inside container
      - /app/start-webui.sh
      # do not touch, commenting this makes webui unavailable to host
      - --server-name=0.0.0.0
      ## ONLY enable if having issues generating images
      #- --always-low-vram
      # COMMENT BELOW if you uncomment above
      - --vae-in-fp32
      # do not touch below 3 lines, they help :)
      - --cuda-malloc
      - --force-upcast-attention
      - --pin-shared-memory
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
    shm_size: '8gb'
