
# docker-compose.yml CPU-only example
services:

  sd-forge:
    # kept in for development, do not uncomment!
    #build: .
    # use the image below :)
    image: catspeedcc/sd-webui-forge-docker:development
    command:
      - /app/webui-docker.sh
      - --server-name=0.0.0.0
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/webui/models
      - ./outputs:/app/webui/outputs