# docker-compose.yml example

services:
  sd-forge:
    #build: .
    image: catspeedcc/sd-webui-forge-docker:development
    command:
      - /app/start-webui.sh
      - --server-name=0.0.0.0
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/webui/models
      - ./outputs:/app/webui/outputs
