
# docker-compose.yml CPU-only example (inherited by others, offloading automatic)
services:

  # CONTAINER SERVICE NAME
  sd-forge-1:
    # kept in for development, do not uncomment!
    #build: .
    # use the 'latest' image below - if this is 'bleeding' please excuse my
    # mistake and please change it back to 'latest' or a version 'v*.*.*' for now :)
    image: catspeedcc/sd-webui-forge-docker:bleeding
    # ABOVE image should be on 'latest' or a version 'v*.*.*'
    environment:
      # # SUPER important this variable is set to the service name above (in this case sd-forge)
      # also you can change it as long as it has "sd-forge" in the name and is unique
      # NO spaces - use dashes
      - DOCKER_SERVICE_NAME=sd-forge-1
      # ABOVE container service names should match
      #
      # This affects the host, not the container.
      # If you are not using the combined compose file _or_ a cut down install using the v1.1.1-sauces.tar.gz
      # Leave this the way it is.
      - IS_CUSTOM_OR_CUTDOWN_INSTALL=false
    command:
      - /app/webui-docker.sh
      - --use-cpu=all
      # SUPER important this variable is set to the service name above (in this case sd-forge)
      # also you can change it as long as it has "sd-forge" in the name and is unique
      # NO spaces - use dashes
      #- --docker-service-name=sd-forge-1
      # ABOVE container service names should match
    ports:
      # THIS is where we limit to localhost (127.0.0.1)
      # or change 127.0.0.1->0.0.0.0 but ensure firewalls properly configured!
      # also ONLY change left side port, do _not_ change the port on the right side
      - "127.0.0.1:7860:7860"
      - "127.0.0.1:7861:7861"
      - "127.0.0.1:7862:7862"
      - "127.0.0.1:7863:7863"
      - "127.0.0.1:7864:7864"
      - "127.0.0.1:7865:7865"
      - "127.0.0.1:7866:7866"
      - "127.0.0.1:7867:7867"
      - "127.0.0.1:7868:7868"
      - "127.0.0.1:7869:7869"
      # Done editing, the rest of the file _should_ be fine in most setups with full GitHub repository
    volumes:
      - ../../models:/app/webui/models
      - ../../outputs:/app/webui/outputs
      - ../../docker:/app/webui/docker
